// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Events.tsx";
import * as $$$$$$1 from "./sections/Foods.tsx";
import * as $$$$$$2 from "./sections/Footer.tsx";
import * as $$$$$$3 from "./sections/Global.tsx";
import * as $$$$$$4 from "./sections/Header.tsx";
import * as $$$$$$5 from "./sections/ItWorks.tsx";
import * as $$$$$$6 from "./sections/Searchbox.tsx";
import * as $$$$$$7 from "./sections/Sponsors.tsx";
import * as $$$$$$8 from "./sections/Testimonials.tsx";
import * as $$$$$$9 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Events.tsx": $$$$$$0,
    "site/sections/Foods.tsx": $$$$$$1,
    "site/sections/Footer.tsx": $$$$$$2,
    "site/sections/Global.tsx": $$$$$$3,
    "site/sections/Header.tsx": $$$$$$4,
    "site/sections/ItWorks.tsx": $$$$$$5,
    "site/sections/Searchbox.tsx": $$$$$$6,
    "site/sections/Sponsors.tsx": $$$$$$7,
    "site/sections/Testimonials.tsx": $$$$$$8,
    "site/sections/Theme/Theme.tsx": $$$$$$9,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
